export const dashboard = '/src/assets/icons/dashboard.png'
export const doctor = '/src/assets/icons/doctor.png'
export const department = '/src/assets/icons/department.png'
export const patient = '/src/assets/icons/patient.png'
export const users = '/src/assets/icons/users.png'